# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths:
      - mydir/**
  pull_request:
    branches: [ "main" ]
    paths:
      - mydir/**

  workflow_dispatch:

jobs:
  deploy-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Configure git
        run: |
          git config --global user.email "devops@madisof.it"
          git config --global user.name "Github Actions"

      - name: Checkout mydir
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set mydir

      - name: Commit
        run: git commit -am "Automated deploy commit $TIMESTAMP"

      - name: Create and push tag
        run: |
          git tag automated-deploy-$TIMESTAMP
          git push origin automated-deploy-$TIMESTAMP

