# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths:
      - mydir/**
  pull_request:
    branches: [ "main" ]
    paths:
      - mydir/**

  workflow_dispatch:

jobs:
  deploy-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove old branch if exists
        run: git branch --delete deploy || true

      - name: Create deploy branch
        run: git checkout -b deploy

      - name: Remove all files
        run: git rm -rf .

      - name: Checkout mydir
        run: git checkout main -- mydir/

      - name: Commit
        run: |
          git config --global user.email "devops@madisof.it"
          git config --global user.name "Github Actions"
          git commit -am "Automated deploy commit"

      - name: Push branch
        run: git push --set-upstream origin deploy

