name: Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - mydir/**
  pull_request:
    branches:
      - main
    paths:
      - mydir/**

jobs:
  create-deploy-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Configure git
        run: |
          git config --global user.email "devops@madisof.it"
          git config --global user.name "Github Actions"

      - name: Create temp branch and checkout mydir
        run: |
          git switch --orphan deploy-$TIMESTAMP
          git checkout main -- mydir/

      - name: Create commit and tag
        run: |
          git commit -am "Automated deploy commit $TIMESTAMP"
          git tag automated-deploy-$TIMESTAMP
      - name: Push tag
        run: git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }} origin automated-deploy-$TIMESTAMP


