# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths:
      - mydir/**
  pull_request:
    branches: [ "main" ]
    paths:
      - mydir/**

  workflow_dispatch:

jobs:
  deploy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set current timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Configure git
        run: |
          mkdir -p $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git init
          git config --global user.email "devops@madisof.it"
          git config --global user.name "Github Actions"
          git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY


      - name: Checkout mydir
        run: |
          echo "mydir/" > .git/info/sparse-checkout
          git config --global core.sparseCheckout true
          git fetch --depth=1 origin $GITHUB_SHA
          git checkout $GITHUB_SHA

      - name: Verify Checkout
        run: |
          ls -la
          du -sh .

      - name: Create and push tag
        run: |
          git tag automated-deploy-$TIMESTAMP
          git push origin automated-deploy-$TIMESTAMP

